# -*- coding: utf-8 -*-
"""TO DO list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10syPwqkS2781JA2-mwltbw7h9pp1PGn8
"""

Todo_list = {}

while True:
    print("To-Do List Menu:")
    print("1. Add task")
    print("2. View tasks")
    print("3. Mark task as done")
    print("4. Remove task")
    print("5. Quit")

    choice = input("Enter your choice (1,2,3,4,5): ")

    if choice == '1':
        task = input("Enter the task: ")
        priority = input("Enter the priority (High, Medium, Low): ").capitalize()
        Todo_list[task] = priority
        print(f"Task '{task}' added to the to-do list.")
    elif choice == '2':
        if not Todo_list:
            print("The to-do list is empty.")
        else:
            print("To-Do List:")
            for task, priority in Todo_list.items():
                print(f"Task: {task}, Priority: {priority}")
    elif choice == '3':
        task = input("Enter the task to mark as done: ")
        if task in Todo_list:
            del Todo_list[task]
            print(f"Task '{task}' marked as done and removed from the to-do list.")
        else:
            print(f"Task '{task}' not found in the to-do list.")
    elif choice == '4':
        task = input("Enter the task to remove: ")
        if task in Todo_list:
            del Todo_list[task]
            print(f"Task '{task}' removed from the to-do list.")
        else:
            print(f"Task '{task}' not found in the to-do list.")
    elif choice == '5':
        break
    else:
        print("Invalid choice. Please enter 1, 2, 3, 4, or 5.")